---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: webinterface
    targetPort: 9200
  - port: 8081
    name: transport
    targetPort: 9300
  selector:
    app: elasticsearch
    role: client
---
